name: Build AppBundle and Upload to AWS

on:
  workflow_dispatch:
    inputs:
      release_aab:
        description: "Build Release AppBundle"
        required: true
        type: choice
        options:
          - "true"
          - "false"
        default: "true"
      release_apk:
        description: "Build Release APK"
        required: false
        type: choice
        options:
          - "true"
          - "false"
        default: "false"
      send_email:
        description: "Send Email with AppBundle and APK links"
        required: false
        type: choice
        options:
          - "true"
          - "false"
        default: "true"

jobs:
  build-and-upload:
    name: Build AppBundle and Upload to AWS
    runs-on: ubuntu-latest
    env:
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGION: ${{ secrets.AWS_REGION }}
      APKNAME: "pixart"
      APPNAME: "PixArt"

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "18"

      # Extract Flutter version from .fvmrc
      - name: Extract Flutter Version
        run: |
          export FLUTTER_VERSION=$(cat .fvmrc | jq -r '.flutter')
          echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "${{ env.FLUTTER_VERSION }}"

      # Restore Keystore
      - name: Decode Keystore File
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/keystore.jks

      # Extract APP_NAME and Version Information
      - name: Extract Metadata
        run: |
          export ANDROID_VERSION_CODE=$(grep ANDROID_VERSION_CODE .env | cut -d '=' -f 2)
          export ANDROID_VERSION_NAME=$(grep ANDROID_VERSION_NAME .env | cut -d '=' -f 2)

          # Set filenames
          export RELEASE_AAB_NAME="${APKNAME}_v${ANDROID_VERSION_NAME}_b${ANDROID_VERSION_CODE}.aab"
          export RELEASE_APK_NAME="${APKNAME}_v${ANDROID_VERSION_NAME}_b${ANDROID_VERSION_CODE}_release.apk"

          echo "RELEASE_AAB_NAME=$RELEASE_AAB_NAME" >> $GITHUB_ENV
          echo "RELEASE_APK_NAME=$RELEASE_APK_NAME" >> $GITHUB_ENV
          echo "ANDROID_VERSION_NAME=$ANDROID_VERSION_NAME" >> $GITHUB_ENV
          echo "ANDROID_VERSION_CODE=$ANDROID_VERSION_CODE" >> $GITHUB_ENV
          echo "${{env.APPNAME}}"

      # Install Dependencies
      - name: Install Dependencies
        run: |
          flutter pub upgrade
          flutter pub get

      # Build Release AppBundle (if requested)
      - name: Build Release AppBundle
        if: ${{ inputs.release_aab == 'true' }}
        run: |
          flutter build appbundle --release \
          --dart-define=KEYSTORE_PATH=android/app/keystore.jks \
          --dart-define=KEYSTORE_ALIAS=$KEYSTORE_ALIAS \
          --dart-define=KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD \
          --dart-define=KEY_PASSWORD=$KEY_PASSWORD

      # Build Release APK (if requested)
      - name: Build Release APK
        if: ${{ inputs.release_apk == 'true' }}
        run: |
          flutter build apk --release \
          --dart-define=KEYSTORE_PATH=android/app/keystore.jks \
          --dart-define=KEYSTORE_ALIAS=$KEYSTORE_ALIAS \
          --dart-define=KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD \
          --dart-define=KEY_PASSWORD=$KEY_PASSWORD

      # Rename Build Files
      - name: Rename Build Files
        run: |
          if [ "${{ inputs.release_aab }}" == "true" ]; then
            mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/${{env.RELEASE_AAB_NAME}}
          fi
          if [ "${{ inputs.release_apk }}" == "true" ]; then
            mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/${{env.RELEASE_APK_NAME}}
          fi

      # Upload Release AppBundle to AWS S3
      - name: Upload Release AppBundle to AWS S3
        if: ${{ inputs.release_aab == 'true' }}
        id: upload_release_aab_s3
        uses: ahkohd/s3-upload-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-bucket: ${{ secrets.AWS_BUCKET_NAME }}
          output-file-url: "true" # specify true
          file-path: "build/app/outputs/bundle/release/${{env.RELEASE_AAB_NAME}}"

      # Upload Release APK to AWS S3
      - name: Upload Release APK to AWS S3
        if: ${{ inputs.release_apk == 'true' }}
        id: upload_release_apk_s3
        uses: ahkohd/s3-upload-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-bucket: ${{ secrets.AWS_BUCKET_NAME }}
          output-file-url: "true" # specify true
          file-path: "build/app/outputs/flutter-apk/${{env.RELEASE_APK_NAME}}"

      # Retrieve Public URLs
      - name: Get Public URLs
        id: get_urls
        run: |
          release_aab_url=""
          release_apk_url=""
          if [ "${{ inputs.release_aab }}" == "true" ]; then
            release_aab_url="${{ steps.upload_release_aab_s3.outputs.file-url }}"
          fi
          if [ "${{ inputs.release_apk }}" == "true" ]; then
            release_apk_url="${{ steps.upload_release_apk_s3.outputs.file-url }}"
          fi

          echo "RELEASE_AAB_URL=$release_aab_url" >> $GITHUB_ENV
          echo "RELEASE_APK_URL=$release_apk_url" >> $GITHUB_ENV

      # Email AppBundle and APK Links (if requested)
      - name: Send Email
        if: ${{ inputs.send_email == 'true' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.dcodax.net
          server_port: 465
          username: "${{ secrets.EMAIL_USERNAME }}"
          password: "${{ secrets.EMAIL_PASSWORD }}"
          from: "${{ secrets.EMAIL_USERNAME }}"
          subject: "New Build - ${{env.APPNAME}} version ${{env.ANDROID_VERSION_NAME}} build ${{env.ANDROID_VERSION_CODE}}"
          body: |
            The following build files have been generated. You can download them from the links below:

            - Release AppBundle: ${{ env.RELEASE_AAB_URL }}
            - Release APK: ${{ env.RELEASE_APK_URL }}

          to: |
            shafiquecbl@gmail.com,
            usamadcodax@gmail.com,
            kanwalusm78@gmail.com,
            talhaali3390137@gmail.com,
            tahagujjar.tg@gmail.com,
            dcodaxtester@gmail.com,
            maqboolsaira7@gmail.com
