name: Push iOS build on TestFlight

on:
  workflow_dispatch:

jobs:
  ios_deployment:
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
      APP_STORE_APP_ID: ${{ secrets.APP_STORE_APP_ID }}
      DISTRIBUTION_CERTIFICATE: ${{ secrets.DIST_CERTIFICATE_BASE64 }}
      DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.DIST_CERTIFICATE_PASSWORD }}
      PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.19.6

      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get
          
      - name: Install the CodeMagic CLI
        run: pip install codemagic-cli-tools

      - name: Initialize keychain
        run: keychain initialize

      - name: Set up Provisioning Profile
        run: |
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          PROFILE_PATH="$(mktemp "$PROFILES_HOME"/$(uuidgen).mobileprovision)"
          echo ${PROVISIONING_PROFILE} | base64 --decode > "$PROFILE_PATH"
          echo "Saved provisioning profile $PROFILE_PATH"   

      - name: Set up Distribution Certificate
        run: |
          echo "MIIMiwIBAzCCDFIGCSqGSIb3DQEHAaCCDEMEggw/MIIMOzCCBr8GCSqGSIb3DQEHBqCCBrAwggasAgEAMIIGpQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIf0PzD++fEasCAggAgIIGeEzMbuM0M2Q9NqnJfycjJ/QQQcof0iFtqunMjS2wS32fM92DL2jYSJLNOjqCxiYdBSvfreP51APKr1Rr/Vk08TtTIW66SDI9vFsiWMjB8K62jql0MlTdd1CCa78oz9Le7i9MGMlvdnZ2CsL72DogWdKdGEqMbbgWBJQHAUap67tf7/xbv2Doh9Gsr5Br9luCKMN98RGkK5AhtnMqbGLXHxoihKKnzr+K1ggXXqw02l9nKzr4ZjT3GQgGh1+7abnPS05RC7IFyU00xytA1B4K7KAEG/kwObyjd392qcN+RE9W4c8BCsDz4O3Z7a0q6iXzzZL5CIGNXYai6GEpnaFL8htvqEnLakK1a1gYWh5pyRzoZxFx2pTsHIWG4nRxbfWZgLL+Jafd263WAWnOSVzUlCDUSUgmIhAF4Nhw9E52K1uHYXNVJCefLzdr3K0gcWqFkb3bo4vdA8aHA2Vxsd+OjDa2va5RDYYcrYfbZqvOfkRbcedEeFw214J4PlAF2jUSFn4m5vJqVesOD4Ga9unKQn50I3GldXtNmI2IStfOycx+Ppw0FgVFPjAs4qeYEe1SeKgcYV4s9sUPGHIUpGTXFBOOphCzf3/9khDgnoPiTF32KrqW2Ny3fw3B41anFy/OvBk/pW+Hf5AmLpMYNI46RBHUg01ESPyuT6eyBzYUG3yiSCwsJbnWz3UUyuvNNI09C3L2grxFBEVutXVgmExHEVM+YLKmJttWeNmQ6Ksk2erDtmp1v6kkxl98gRzUWNyTRxzXszaqW9DA8uqKEsT5MEsh3F6T1SvylqEG6afpkgFTBxqFnxz/qSz8fweFze4CEBK10sPNCfW9v221p5MJ2GjBlgFP8SUOtFZZ+ignOLRveAie5DT9ijm1I+TYePSQC5MXGJicenL9UVUYJUs6SzeK5+YyFpg22hYy+jqo0CWSDK4yEV6OeqUeyd7xt+9f3afigruG66YRjlEOaqYRAjslgTKFs5z1caXvvORX5SmfyLygBjqX4Mju1IygRPu6okJEC3STpf2BqBUOe9Xd5F86Si5toi4cqA2oyzVoQyf037gXqBtMvgXgZdZX8tFIHvZfkhLpNzpTBWctxnOUXtWAjBrHMutP+gwWYH3Dyg+R9A6KPFZNOqcwaz7Px75jiPE/PVhBTztWS9ZSQOlydnAAuEmqiK/5iPJrZBgcKg7LEMUhGpZgmvk70NDH/AKTbOB3JM7XIQBI9czd8hMFX22nM/GdKMCHN6/TecY55mw9hO2XknFiK65YR3NZTUaQZbdW0BnmS1JWPgq3cLZSsj0N8yo8kSq2vMJXM6U96KcIqHV4H6mG7hmnkeK13n3sg1DPNqwC00biM9Ybzc2WdZhoTPGbn9s1PrPQWFQMdbXkN799z251bjkjZS+BlkkzFi/eXNO+f180cgiaW04/HIgqVOOs5BenLRqYe0OUTKSlnBmIc8ZblqDLrOurDL4dvxS/Nkq7oECHB6UtTP2piiFSPkjnE6DPvwNre0GJ0XZMDy9mThXOnJx3SXvamjVhy/kq4XNltKdBTOshLs3bitDf2f8OcBeWEVnBzv+djsSg1k7JFUDJuXLqUZ0HOLvcXq0BNcdlNfeHwy7qFoknKjAtV8pqQDYSgfibuNZhvzkKTSYiz74jlwxRve9WnGMRlhZFBBUAN3KmAYDBv/yhU6g2fBRRvaLnotZwYQhfyTXEGSydVaxG+QKIEPeVH2N57lu2M1SFXVFXAEMVbI3lu9iCEt/jPTIcwN2t12ZSsS9hxJdGZaf3CWooUF/kAkh2N2JXe+oSz3P0allgcrgnntj0iQbQV7JU2bAWSJvDx5wZfEDgUhzc8kDKaIGGgMKmCT7YxkkVYUJ/hn/vrVr3XslhNaGPtSC0btNiPix6zooFL+AxdZkvAbIn2WEYMlzSvxqZbB/R5BcqI39E+jdurZ/H1VyDRJteY6qYOxNoIfX3oG6i3jh6jaldlOVHE1qAHEUQ5TgqfRegui/1coTfxykQqWCTpixD/CV0NyXqdacUcaDsJ8H58QqlZbqp9okXyO8Ghc0tHbuwm5TACk5HpHk7P7qnw58uVITGH5+Unk1SCHszZAR5NChInNRky5zlI9TH5Tm6vdbVrTeJsDDbaJTc1khY5ieihB8+7JckpOmgWl5TmUf0AwR3B8viiv1FXZ+F5p+9RJqrRCWfsIb7cBmCTPhdMSHw9jCCBXQGCSqGSIb3DQEHAaCCBWUEggVhMIIFXTCCBVkGCyqGSIb3DQEMCgECoIIE7jCCBOowHAYKKoZIhvcNAQwBAzAOBAhWMdkd6o2NsQICCAAEggTIcMsG0m/qkNW56iNtfSQq2BzxnwNGrBW6Py2dUNkEmndp2wFACZh6Kg2+gRCkprs5fjX2QoXRW2k3bdf4hAliD69Aidi54ybzFm0AEoOtooZqXZfDHpOBmwygTmPOA/IgfjGyxkWZ+bsI/Q1aLh0oB3/wCxDLGnOHvB9kRR4V6r5iJ7LGnT8bQD7pVWSCN812KYd0F5MQWhrB778W9v74IStMe4Lfv4ZaXWOBeBfAO3wNHhcLD1CvliK7hJgGsHQaT4Sx0fU43G+4N+Nxsbt9rnVZ1NEqta1kaYDMlNh7aQL7Oi/Dfo8/1QUsqMWQUeZiFWjNbxTy7i/F2p+i5FlwysWLqdG5SADJZcAz7O6QyFN6rkddVY8DKQKXWOCaJk740/PS/z4rvxpFGBzQq0xeMQXWWcg6OqgodgUJgiNyktMg5orlEZrWjVnAO2dOTQyjoTDvPGGafSSIZtRbZRb3J/KtBr0BZbvLy/S6s/5LXwz5hc6P3tIm9yfD7HakQpH7HKzC4QeE/BKv9/uw42HMSl5FyOvSRY45vdSJsMKV2szOUATIVqMNP5FaqhUDaYovVWvRp+94Qn7XYegqfC8ALFA8MBMZyVZour/p8E1De1BRJrJ252PZofBg9clSUOJ0suuT/WBoU236i3LCuFj3TTZEYFBvC4RX1Jm/VlvvtbPT2UzQKSP+4sz7qpE3TYiF1SZdDW1e06XbcBgCCa4C/6Q2Qf5xdwa8EB7jj0z0lQrawzxsi4xmjYSMie1e2QileZ+MSfCzPhcwrwtgqwaWh7CDzckj7ZX2ypatM+2QNf1xmkc9EbNLXTrEQitz3T9QaPenHovqXv7cLptLCmuw/HnoH0/fdDpMqEwqJ65PIJkxYDk3HJoWcNLg54s06lMsF6sms0NxKJTUu8oNu9EJpbM61kig7v4DwuC6yDzzpyphbPqMWYDHgnN22cHVmwMwGh0OoEfMTX0mqI27zLEoAZKjXuXTB2NApBSqyRvqQlzt1t132BxVxh03PjEUCEoJkAaQBCbVMCM0KijecH8whZk4MuuurHuMvZttzZSuEpYo/y3fP53/w3ZvcKDKuBw3CnIJe2h538kraHygxhW/AdrRV0huk/nefhdiJgakdR4FPLQIqXnr+/V0NS/nCUe+cdjsE/yZ4h9VuKrg8D/cpQwPYkH+oY5oL5HwB358of0QNHDmKBaAAnuWI5tOb8PIBRZ8xN4O/UNEGorJyu4N+pAT3VqYagYmDzjzYAEcTL/PNigaOJ/0lfdtmuh8+ze+zgliJpP24kXMAycbrRvWqgHRKz/MWAIuUK4nVCs8u5dUDBbMU5SJjgQar3fNpzywKdTnUeB1Tcv6e8hcXWVLc6LTI6NNO1TViqvxQySdWCqVxvzghH0c3BsOcr8++PEc+cwWnS8nXjqovS+Z82KVovFELRoarmWLO+d0vU3BeAAXis+gsR38uOlsnlGmfXIihkwvtubEWQ98JovzHwMwMYOmxRLsn1j2kx1XE+oHx9ducN+I5qBa6MkyMUD5utpkf42bKEqgI4fbzzxFbGlGI/f8smD7bJzQXt7y8yofY49OmOzrmqPIrwcQuF9DS0c6D3mA8XoWKtRJW2hglpIdAzN90TgStsVYMVgwMQYJKoZIhvcNAQkUMSQeIgBNAHUAaABhAG0AbQBhAGQAIABTAGgAYQBmAGkAcQB1AGUwIwYJKoZIhvcNAQkVMRYEFLVQ8UUvdST7PQZRZb3YDDJI38FJMDAwITAJBgUrDgMCGgUABBRMirLqczIYKqGYX5S/z54inD0ZFwQIr28PabP/aSoCAQE=" | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password "Dcodax@1234"

      - name: Extract Version and Build Number from Environment.xcconfig
        run: |
          # Extract MARKETING_VERSION
          export MARKETING_VERSION=$(grep MARKETING_VERSION ios/Flutter/Environment.xcconfig | sed 's/[^0-9.]*//g')
          echo "MARKETING_VERSION=$MARKETING_VERSION" >> $GITHUB_ENV

          # Extract CURRENT_PROJECT_VERSION
          export CURRENT_PROJECT_VERSION=$(grep CURRENT_PROJECT_VERSION ios/Flutter/Environment.xcconfig | sed 's/[^0-9]*//g')
          echo "CURRENT_PROJECT_VERSION=$CURRENT_PROJECT_VERSION" >> $GITHUB_ENV

      - name: Set up Code signing settings on Xcode project
        run: xcode-project use-profiles

      - name: Build IPA for Distribution
        run: |
          # Calculate dynamic build number
          buildNumber=$((CURRENT_PROJECT_VERSION + ${{ github.run_number }}))
          echo "Building app with version $MARKETING_VERSION and build number $buildNumber"
          
          # Build the app
          flutter build ipa --release --build-name=$MARKETING_VERSION --build-number=$buildNumber --export-options-plist=$HOME/export_options.plist

      - name: Upload IPA to App Store Connect
        run: |
          # Find the generated IPA file
          APP_FILE=$(find $(pwd) -name "*.ipa")
          echo "Uploading build with file: $APP_FILE"

          # Upload to App Store Connect
          app-store-connect publish \
            --path "$APP_FILE" 
