name: Push iOS build on TestFlight

on:
  workflow_dispatch:

jobs:
  ios_deployment:
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNCET_ISSUER_ID }}
      APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
      APP_STORE_APP_ID: ${{ secrets.APP_STORE_APP_ID }}
      DISTRIBUTION_CERTIFICATE: ${{ secrets.DIS_CERTIFICATE_BASE64 }}
      DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.DIST_CERTIFICATE_PASSWORD }}
      PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}

    steps:
      - name: Set up Xcode 15.2
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app
          xcodebuild -version
          pod --version

      - name: Set up Cocapods (1.15.2)
        run: |
          sudo gem uninstall cocoapods
          sudo gem install cocoapods -v 1.15.2
          pod --version
  
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.19.6

      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Install flutter fire
        run: |
          npm install -g firebase-tools
          dart pub global activate flutterfire_cli
          
      - name: Install pods (pod install)
        run: |
          cd ios
          pod install
          
      - name: Install the CodeMagic CLI
        run: pip install codemagic-cli-tools

      - name: Initialize keychain
        run: keychain initialize

      - name: Set up Provisioning Profile
        run: |
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          PROFILE_PATH="$(mktemp "$PROFILES_HOME"/$(uuidgen).mobileprovision)"
          echo ${PROVISIONING_PROFILE} | base64 --decode > "$PROFILE_PATH"
          echo "Saved provisioning profile $PROFILE_PATH"   

      - name: Set up Distribution Certificate
        run: |
          echo "${DISTRIBUTION_CERTIFICATE}" | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password "${DISTRIBUTION_CERTIFICATE_PASSWORD}"

      - name: Extract Version and Build Number from Environment.xcconfig
        run: |
          # Extract MARKETING_VERSION
          export MARKETING_VERSION=$(grep MARKETING_VERSION ios/Flutter/Environment.xcconfig | sed 's/[^0-9.]*//g')
          echo "MARKETING_VERSION=$MARKETING_VERSION" >> $GITHUB_ENV

          # Extract CURRENT_PROJECT_VERSION
          export CURRENT_PROJECT_VERSION=$(grep CURRENT_PROJECT_VERSION ios/Flutter/Environment.xcconfig | sed 's/[^0-9]*//g')
          echo "CURRENT_PROJECT_VERSION=$CURRENT_PROJECT_VERSION" >> $GITHUB_ENV
      
      - name: Set up Code signing settings on Xcode project
        run: xcode-project use-profiles

      - name: Build IPA for Distribution
        run: |
          # Build the app
          flutter build ipa --release --build-name=$MARKETING_VERSION --build-number=$CURRENT_PROJECT_VERSION --export-options-plist=$HOME/export_options.plist

      - name: Upload IPA to App Store Connect
        run: |
          # Find the generated IPA file
          APP_FILE=$(find $(pwd) -name "*.ipa")
          echo "Uploading build with file: $APP_FILE"

          # Upload to App Store Connect
          app-store-connect publish \
            --path "$APP_FILE" 
